export const routes = [
  '/',
  '/nursing-officer-exams-in-india',
  '/aiims-norcet-exam',
  '/rrb-nursing-superintendent-exam',
  '/esic-nursing-officer-exam',
  '/jipmer-nursing-officer-exam',
  '/nhm-nursing-officer-recruitment',
  '/nursing-officer-eligibility',
  '/nursing-officer-salary',
  '/government-hospitals-nursing-officer-recruitment',
  '/how-to-apply-for-nursing-officer-exam',
  '/privacy-policy',
  '/disclaimer',
] as const;
